### ISSUE TITLE
Unknown flag `path`

### ISSUE THREAD

**Issue by Demetri0** [vk-en/fioplot-bs#3]
Hello, I am trying to run `fioplot-bs` step by step, following `README.md` but, I've got an error on the next step:

![Screenshot from 2022-07-18 23-38-53](https://user-images.githubusercontent.com/6806547/179570647-b366b2aa-d5d8-45ef-8fb4-b268ee7cd14d.png)

I've got:

![Screenshot from 2022-07-18 23-36-15](https://user-images.githubusercontent.com/6806547/179570023-c77278e3-c176-497d-9b1f-c76ef1b19e20.png)

What am I doing wrong?

**Comment by vk-en** [comment]
👋 Hi Demetri0!

Thanks for your input😊

Usually, all available options can be viewed by calling the command:
`./fioplot-bs -h`

Also in PR #4 , the instruction (in README) has been corrected in accordance with the latest changes in the code.

**Comment by Demetri0** [comment]
Thank you for explaining!
